/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Abyssal Precision design system
        "surface":                    "#10131a",
        "surface-dim":                "#10131a",
        "surface-bright":             "#363940",
        "surface-container-lowest":   "#0b0e14",
        "surface-container-low":      "#191c22",
        "surface-container":          "#1d2026",
        "surface-container-high":     "#272a31",
        "surface-container-highest":  "#32353c",
        "on-surface":                 "#e1e2eb",
        "on-surface-variant":         "#b9cacb",
        "outline":                    "#849495",
        "outline-variant":            "#3a494b",
        "surface-variant":            "#32353c",
        "surface-tint":               "#00dbe7",
        // Primary (cyan)
        "primary":                    "#e1fdff",
        "on-primary":                 "#00363a",
        "primary-container":          "#00f2ff",
        "on-primary-container":       "#006a71",
        "primary-fixed":              "#74f5ff",
        "primary-fixed-dim":          "#00dbe7",
        "on-primary-fixed":           "#002022",
        "on-primary-fixed-variant":   "#004f54",
        "inverse-primary":            "#00696f",
        // Secondary (blue)
        "secondary":                  "#b3c5ff",
        "on-secondary":               "#002b75",
        "secondary-container":        "#0266ff",
        "on-secondary-container":     "#f9f7ff",
        "secondary-fixed":            "#dae1ff",
        "secondary-fixed-dim":        "#b3c5ff",
        "on-secondary-fixed":         "#001849",
        "on-secondary-fixed-variant": "#003fa4",
        // Tertiary (green)
        "tertiary":                   "#e1ffec",
        "on-tertiary":                "#003824",
        "tertiary-container":         "#67f4b7",
        "on-tertiary-container":      "#006e4b",
        "tertiary-fixed":             "#6ffbbe",
        "tertiary-fixed-dim":         "#4edea3",
        "on-tertiary-fixed":          "#002113",
        "on-tertiary-fixed-variant":  "#005236",
        // Error
        "error":                      "#ffb4ab",
        "on-error":                   "#690005",
        "error-container":            "#93000a",
        "on-error-container":         "#ffdad6",
        // Background
        "background":                 "#10131a",
        "on-background":              "#e1e2eb",
        // Inverse
        "inverse-surface":            "#e1e2eb",
        "inverse-on-surface":         "#2e3037",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
      spacing: {
        base:   "4px",
        xs:     "8px",
        sm:     "16px",
        gutter: "16px",
        md:     "24px",
        lg:     "32px",
        margin: "32px",
        xl:     "48px",
      },
      fontFamily: {
        inter:         ["Inter", "system-ui", "sans-serif"],
        // Abyssal Precision tipografi token'ları (hepsi Inter — font-size text-* ile birlikte kullanılır)
        "display-xl":  ["Inter", "system-ui", "sans-serif"],
        "headline-lg": ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        "body-lg":     ["Inter", "system-ui", "sans-serif"],
        "body-md":     ["Inter", "system-ui", "sans-serif"],
        "data-tabular":["Inter", "system-ui", "sans-serif"],
        "label-sm":    ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg":     ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":     ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-tabular":["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm":    ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
